#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/malamachiluwe/Programming/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/malamachiluwe/AndroidStudioProjects/flutter-house-rent"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/malamachiluwe/AndroidStudioProjects/flutter-house-rent/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "CONFIGURATION_BUILD_DIR=/Users/malamachiluwe/AndroidStudioProjects/flutter-house-rent/build/ios/iphoneos"
export "DART_DEFINES=Zmx1dHRlci5pbnNwZWN0b3Iuc3RydWN0dXJlZEVycm9ycz10cnVl,RkxVVFRFUl9WRVJTSU9OPTMuMzEuMC0xLjAucHJlLjMzMQ==,RkxVVFRFUl9DSEFOTkVMPW1hc3Rlcg==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049MTI3MjIwYzkwOQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MjZhZDkyMTA1ZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My44LjAgKGJ1aWxkIDMuOC4wLTI0My4wLmRldik="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/malamachiluwe/AndroidStudioProjects/flutter-house-rent/.dart_tool/package_config.json"
